name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/anyakichi/fastapi-sample:main
    steps:
      - uses: actions/checkout@v2
      - run: poetry install
      - run: poetry run poe lint
      - run: poetry run poe test
